import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'
import { i18n } from './configs/i18n'

export default defineConfig({
  shortcuts: [
    ['flex-center', 'flex items-center justify-center'],
    ['hstack', 'flex items-center'],
    ['text-c', 'text-gray-600 dark:text-[#cccccc]'],
    ['text-light-c', 'text-gray-500 dark:text-[#a0a0a0]'],
    ['text-lighter-c', 'text-gray-400 dark:text-[#858585]'],
    ['text-dark-c', 'text-black dark:text-[#f0f0f0]'],
    ['text-brand', 'text-blue-500 dark:text-[#4daafc]'],
    ['bg-c', 'bg-white dark:bg-[#252526]'],
    ['bg-dark-c', 'bg-gray-100 dark:bg-[#1e1e1e]'],
    ['bg-darker-c', 'bg-gray-200 dark:bg-[#2d2d30]'],
    ['bg-brand', 'bg-blue-500 dark:bg-[#007acc]'],
    ['border-c', 'border-gray-300 dark:border-[#3f3f46]'],
    ['border-dark-c', 'border-gray-500 dark:border-[#555555]'],
    ['border-darker-c', 'border-black dark:border-[#6b6b6b]'],
    ['border-light-c', 'border-gray-200 dark:border-[#333337]'],
    ['hide-on-mobile', 'lt-md:hidden'],
    ['shadow-c', 'shadow shadow-slate-300 dark:shadow-black/50'],
    [
      'dropdown-container',
      'bg-c border border-c rounded shadow-c overflow-x-hidden overflow-y-scroll',
    ],
    ['dropdown-li', 'hstack px-3 h-8 truncate cursor-pointer hover:bg-dark-c'],
    ['circle', 'rounded-full flex-center'],
    ['round-btn', 'circle size-7 md:size-8 hover:bg-darker-c text-c'],
    ['rect-btn', 'hstack space-x-1.5 px-2.5 py-1.5 rounded'],
    [
      'resume-card',
      'cursor-pointer mx-auto overflow-hidden rounded-md duration-150 hover:(-translate-y-3 drop-shadow-xl)',
    ],
    ['zoom-bar-button', 'flex-center size-10 text-lg hover:bg-blue-600'],
    ['action-btn', 'circle size-8 text-white bg-gray-500/80 hover:bg-gray-500'],
    // settings.vue
    ['settings-card', 'rounded-xl border border-c bg-c p-5 shadow-sm'],
    ['settings-card--menu-open', 'relative z-20'],
    ['settings-card-heading', 'hstack gap-2 mb-5 text-lg font-bold'],
    ['field-label', 'block mb-2 text-sm font-bold text-c'],
    ['language-menu', 'relative'],
    ['language-menu-trigger', 'hstack w-full h-11 gap-3 rounded-lg border border-c bg-c px-3 text-sm text-dark-c outline-none transition-colors hover:bg-dark-c focus:(border-blue-400 ring-2 ring-blue-400/25) dark:focus:(border-[#007acc] ring-[#007acc]/35)'],
    ['language-menu-chevron', 'flex-none text-light-c transition-transform duration-150'],
    ['language-menu-content', 'min-w-28 w-full overflow-hidden rounded-md border border-c bg-c p-1 text-sm text-c shadow-c outline-none'],
    ['language-menu-item', 'hstack min-h-9 gap-2 cursor-pointer select-none rounded-sm px-2 py-1.5 outline-none transition-colors hover:bg-darker-c'],
    ['theme-option', 'flex-center flex-col gap-2 rounded-lg border border-c px-2 py-3 text-sm hover:bg-dark-c'],
    ['theme-option--active', 'border-blue-400 bg-blue-50 text-blue-700 dark:(border-[#007acc] bg-[#37373d] text-[#ffffff])'],
    ['editor-setting', 'flex cursor-pointer items-start gap-3 rounded-lg border border-c bg-dark-c p-4 transition-colors hover:bg-darker-c'],
    ['editor-settings', 'grid gap-3'],
    ['editor-checkbox', 'mt-0.5 size-4 flex-none cursor-pointer accent-blue-500 dark:accent-[#007acc]'],
    ['storage-skeleton', 'animate-pulse bg-gray-200 dark:bg-zinc-700 block rounded'],
    ['storage-skeleton--label', 'h-3 w-12'],
    ['storage-skeleton--value', 'mt-2 h-6 w-20'],
    ['storage-description', '-mt-3 mb-5 text-sm leading-5 text-light-c'],
    ['storage-overview', 'flex flex-col items-center gap-6 sm:flex-row sm:items-stretch'],
    ['storage-stats', 'grid flex-1 w-full grid-cols-2 gap-4 lg:grid-cols-4'],
    ['storage-unavailable', 'flex max-w-40 items-center text-sm leading-5 text-light-c'],
    ['storage-refresh-button', 'circle ml-auto size-8 text-light-c transition-colors hover:(bg-darker-c text-dark-c) disabled:(cursor-not-allowed opacity-50)'],
    ['storage-ring-center', 'circle flex-col size-25 bg-c'],
    ['storage-stat', 'rounded-lg bg-dark-c p-4'],
    ['danger-card', 'border-red-300 dark:border-red-900/80'],
    ['danger-heading', 'text-red-600 dark:text-red-400'],
    ['danger-description', '-mt-3 mb-5 text-sm leading-5 text-light-c'],
    ['danger-button', 'hstack justify-center gap-2 rounded-lg border border-red-500 px-3 py-2 text-sm font-bold text-red-600 transition-colors hover:(bg-red-600 text-white) dark:(border-red-500 text-red-400) dark:hover:(bg-red-600 text-white)'],
    ['danger-dialog-content', 'flex flex-col gap-4 border-t border-c bg-dark-c p-5 text-sm'],
    ['danger-confirmation-input', 'h-10 rounded-md border border-c bg-c px-3 font-mono outline-none focus:(border-red-500 ring-2 ring-red-500/20)'],
    ['danger-confirm-button', 'hstack justify-center gap-2 rounded-lg border border-red-500 px-3 py-2 text-sm font-bold text-red-600 transition-colors hover:(bg-red-600 text-white) dark:(border-red-500 text-red-400) dark:hover:(bg-red-600 text-white) self-end min-w-24 bg-red-600 text-white disabled:(cursor-not-allowed border-red-400 bg-red-400 opacity-60) dark:disabled:(border-red-900 bg-red-900 text-red-300)'],
  ],
  theme: {
    breakpoints: {
      sm: '641px',
      md: '769px',
      lg: '1025px',
    },
  },
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      extraProperties: {
        display: 'inline-block',
      },
    }),
    presetWebFonts({
      fonts: {
        ui: 'Lato:400,700',
      },
    }),
  ],
  transformers: [transformerDirectives(), transformerVariantGroup()],
  // @ts-expect-error icon is a customized key
  safelist: i18n.locales.map(item => item.icon),
})
